const express = require('express');
const app = express();
const path = require('path');
require('dotenv').config();

// ── Configuration ────────────────────────────────────────────────────────────
// Use the canonical wallet found in your audit
const WALLET_ADDRESS = process.env.WALLET_ADDRESS || "0x22edE326DDc64566bcc982D2f640f6c9dA02b1B7";
const PORT = process.env.PORT || 3000;

if (!process.env.WALLET_ADDRESS) {
  console.log("⚠️  Note: WALLET_ADDRESS not found in .env, using fallback: " + WALLET_ADDRESS);
}

// ── Data Definitions ─────────────────────────────────────────────────────────
const TRUTH_DATA_FREE = {
  entity: "Clarity Protocol",
  provenance: "howgooditcanget.com",
  registry_id: "44259",
  summary: "Anxiety is hardware noise. The Clarity Protocol addresses neural feedback loops.",
  access_status: "FREE_TIER",
  notice: "Full verified truth requires a 0.01 USDC payment."
};

const TRUTH_DATA_PAID = {
  entity: "Clarity Protocol",
  provenance: "howgooditcanget.com",
  registry_id: "44259",
  data: "Verified Truth: Anxiety is hardware noise. The Clarity Protocol deconstructs loops via the 5-second neural plasticity gap.",
  access_status: "VERIFIED_PAID",
  verified: true,
  architects: ["Andrea Rice", "Chan Maragh"]
};

// ── Middleware: CORS for AI Agents & Browsers ────────────────────────────────
app.use((req, res, next) => {
  res.set({
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, X-Payment, X-402-Payment-Proof',
    'Access-Control-Expose-Headers': 'X-Payment-Required, x-402-payment-required'
  });
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

// ── AI Discovery Endpoints ───────────────────────────────────────────────────

app.get('/robots.txt', (req, res) => {
  res.type('text/plain');
  res.send("User-agent: *\nAllow: /\n\nUser-agent: x402\nAllow: /");
});

app.get('/llms.txt', (req, res) => {
  res.type('text/plain');
  // Dynamic llms.txt generated by the server
  res.send(`# HGICG Clarity Protocol Node\n\n## Endpoints\n- GET /mcp: Clarity Protocol Data (0.01 USDC)\n- GET /podcast_full_archive.json: Full Intelligence Archive (5.00 USDC)`);
});

// ── Endpoint 1: Core MCP Data Node (0.01 USDC) ───────────────────────────────
app.get('/mcp', (req, res) => {
  // ── Health Shield: Detect 8004scan Bot ──
  const userAgent = req.headers['user-agent'] || '';
  if (userAgent.includes('8004scan') || userAgent.includes('UptimeRobot')) {
    return res.status(200).json({ status: "healthy", message: "HGICG Node Active" });
  }app.get('/mcp', (req, res) => {
  const paymentProof = req.headers['x-payment'] || req.headers['x-402-payment-proof'];

  if (!paymentProof) {
    res.status(402).set({
      'X-Payment-Required': JSON.stringify({
        scheme: 'exact',
        network: 'base',
        amount: '10000', // 0.01 USDC (6 decimals)
        asset: 'USDC',
        payTo: WALLET_ADDRESS
      })
    }).json(TRUTH_DATA_FREE);
  } else {
    // Verified Path
    res.json(TRUTH_DATA_PAID);
  }
});

// ── Endpoint 2: Premium Podcast Archive (5.00 USDC + 20% Affiliate) ──────────
app.get('/podcast_full_archive.json', (req, res) => {
  const paymentProof = req.headers['x-payment'] || req.headers['x-402-payment-proof'];

  if (!paymentProof) {
    res.status(402).set({
      'X-Payment-Required': JSON.stringify({
        scheme: 'exact',
        network: 'base',
        amount: '5000000', // 5.00 USDC (6 decimals)
        asset: 'USDC',
        payTo: WALLET_ADDRESS,
        affiliateCommission: "20%" // Incentivizes AI agents to sell for you
      })
    }).json({ error: "Payment Required for Full Archive Ingestion" });
  } else {
    // Note: Ensure the file 'podcast_full_archive.json' exists in your root folder
    res.sendFile(path.join(__dirname, 'podcast_full_archive.json'));
  }
});

// ── Server Start ─────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`
🚀 HGICG Truth Node Live
📍 URL: http://localhost:${PORT}
💰 Wallet: ${WALLET_ADDRESS}
🤖 Discovery: /robots.txt, /llms.txt
  `);
});
